const packagesList = [
  {
    id: 1,
    name: "Simply Gangtok",
    category: ["Family with Kids", "Shopping"],
    duration: 4,
    nights: 3,
    destinations: ["Gangtok"],
    startingPrice: 20000,
    currency: "₹",
    image: "https://s7ap1.scene7.com/is/image/incredibleindia/spiritual-spots-in-pelling-popular?qlt=82&ts=1726655959297,3",
    inclusions: ["Hotel", "Transfer", "Sightseeing", "Meals"],
    coordinates: {
      latitude: 27.3389,
      longitude: 88.6065,
      latitudeDelta: 0.1,
      longitudeDelta: 0.1,
    },
    itinerary: [
      {
        day: 1,
        morning: "Arrive Bagdogra",
        noon: "On to Gangtok",
        evening: "Overnight in Gangtok",
      },
      {
        day: 2,
        morning: "On to Gangtok",
        noon: "City Tour of Gangtok",
        evening: "Overnight in Gangtok",
      },
      {
        day: 3,
        morning: "Trip to Tsomgo Lake",
        noon: "Trip to Baba Mandir",
        evening: "Overnight in Gangtok",
      },
      {
        day: 4,
        morning: "Depart Bagdogra Airport",
        noon: "",
        evening: "",
      },
    ],
    pricing: {
      packageCost: 40000,
      gst: 2000,
      grandTotal: 42000,
      gstPercentage: 5,
    },
    roomsGuests: {
      rooms: 1,
      guests: 2,
    },
    priceCategory: "Standard",
    fromCity: "Bagdogra (Land Only)",
    rating: 4.8,
    reviews: 156,
    description: "A perfect family getaway to the serene hills of Gangtok with comfortable accommodation and guided sightseeing tours.",
  },
  {
    id: 2,
    name: "Gangtok and Darjeeling Special",
    category: ["Family with Kids"],
    duration: 5,
    nights: 4,
    destinations: ["Darjeeling", "Gangtok"],
    startingPrice: 27625,
    currency: "₹",
    image: "https://www.tourmyindia.com/states/sikkim/images/rumtek1.jpg",
    inclusions: ["Hotel", "Transfer", "Sightseeing", "Meals"],
    coordinates: {
      latitude: 27.0360,
      longitude: 88.2627,
      latitudeDelta: 0.2,
      longitudeDelta: 0.2,
    },
    itinerary: [
      {
        day: 1,
        morning: "Arrive Bagdogra",
        noon: "Transfer to Darjeeling",
        evening: "Overnight in Darjeeling",
      },
      {
        day: 2,
        morning: "Darjeeling sightseeing",
        noon: "Tiger Hill, Batasia Loop",
        evening: "Overnight in Darjeeling",
      },
      {
        day: 3,
        morning: "Transfer to Gangtok",
        noon: "Check-in hotel",
        evening: "Overnight in Gangtok",
      },
      {
        day: 4,
        morning: "Gangtok city tour",
        noon: "Local monasteries visit",
        evening: "Overnight in Gangtok",
      },
      {
        day: 5,
        morning: "Departure",
        noon: "Transfer to Bagdogra",
        evening: "",
      },
    ],
    pricing: {
      packageCost: 52000,
      gst: 2600,
      grandTotal: 54600,
      gstPercentage: 5,
    },
    roomsGuests: {
      rooms: 1,
      guests: 2,
    },
    priceCategory: "Standard",
    fromCity: "Bagdogra",
    rating: 4.7,
    reviews: 203,
    description: "Experience the best of both hill stations - the tea gardens of Darjeeling and the Buddhist culture of Gangtok.",
  },
  {
    id: 3,
    name: "Darjeeling and Gangtok Durga Puja Special",
    category: ["Family with Kids"],
    duration: 6,
    nights: 5,
    destinations: ["Darjeeling", "Gangtok"],
    startingPrice: 33750,
    currency: "₹",
    image: "https://s7ap1.scene7.com/is/image/incredibleindia/phodong-monastery-gangtok-sikkim-gangtok-1-musthead-hero?qlt=82&ts=1742153343325",
    inclusions: ["Hotel", "Transfer", "Sightseeing", "Meals"],
    coordinates: {
      latitude: 27.0360,
      longitude: 88.2627,
      latitudeDelta: 0.2,
      longitudeDelta: 0.2,
    },
    itinerary: [
      {
        day: 1,
        morning: "Arrive Bagdogra",
        noon: "Transfer to Darjeeling",
        evening: "Durga Puja celebrations",
      },
      {
        day: 2,
        morning: "Tiger Hill sunrise",
        noon: "Darjeeling sightseeing",
        evening: "Local Puja pandals visit",
      },
      {
        day: 3,
        morning: "Tea garden visit",
        noon: "Toy train ride",
        evening: "Cultural programs",
      },
      {
        day: 4,
        morning: "Transfer to Gangtok",
        noon: "Check-in hotel",
        evening: "Local exploration",
      },
      {
        day: 5,
        morning: "Gangtok monastery tour",
        noon: "Tsomgo Lake excursion",
        evening: "Traditional dinner",
      },
      {
        day: 6,
        morning: "Departure",
        noon: "Transfer to airport",
        evening: "",
      },
    ],
    pricing: {
      packageCost: 63000,
      gst: 3150,
      grandTotal: 66150,
      gstPercentage: 5,
    },
    roomsGuests: {
      rooms: 1,
      guests: 2,
    },
    priceCategory: "Festival Special",
    fromCity: "Bagdogra",
    rating: 4.9,
    reviews: 89,
    description: "Special festive package during Durga Puja season with cultural experiences and traditional celebrations.",
  },
  {
    id: 4,
    name: "Sikkim Complete Tour",
    category: ["Adventure", "Family with Kids"],
    duration: 7,
    nights: 6,
    destinations: ["Gangtok", "Pelling", "Yuksom"],
    startingPrice: 45000,
    currency: "₹",
    image: "https://s7ap1.scene7.com/is/image/incredibleindia/pemayangtse-monastery-pelling-sikkim-2-attr-hero?qlt=82&ts=1726656027807,2",
    inclusions: ["Hotel", "Transfer", "Sightseeing", "Meals", "Permits"],
    coordinates: {
      latitude: 27.5330,
      longitude: 88.5122,
      latitudeDelta: 0.5,
      longitudeDelta: 0.5,
    },
    itinerary: [
      {
        day: 1,
        morning: "Arrive NJP/Bagdogra",
        noon: "Transfer to Gangtok",
        evening: "Rest and acclimatization",
      },
      {
        day: 2,
        morning: "Gangtok local sightseeing",
        noon: "Monastery visits",
        evening: "MG Marg exploration",
      },
      {
        day: 3,
        morning: "Excursion to Tsomgo Lake",
        noon: "Baba Harbhajan Singh Mandir",
        evening: "Return to Gangtok",
      },
      {
        day: 4,
        morning: "Transfer to Pelling",
        noon: "Check-in and rest",
        evening: "Kanchenjunga view",
      },
      {
        day: 5,
        morning: "Pelling sightseeing",
        noon: "Pemayangtse Monastery",
        evening: "Skywalk experience",
      },
      {
        day: 6,
        morning: "Transfer to Yuksom",
        noon: "Dubdi Monastery visit",
        evening: "Nature walk",
      },
      {
        day: 7,
        morning: "Departure",
        noon: "Transfer to airport",
        evening: "",
      },
    ],
    pricing: {
      packageCost: 84000,
      gst: 4200,
      grandTotal: 88200,
      gstPercentage: 5,
    },
    roomsGuests: {
      rooms: 1,
      guests: 2,
    },
    priceCategory: "Deluxe",
    fromCity: "NJP/Bagdogra",
    rating: 4.8,
    reviews: 127,
    description: "Comprehensive tour covering major destinations in Sikkim with comfortable stays and guided tours.",
  },
  {
    id: 5,
    name: "North Sikkim Adventure",
    category: ["Adventure", "Photography"],
    duration: 8,
    nights: 7,
    destinations: ["Gangtok", "Lachung", "Lachen", "Gurudongmar Lake"],
    startingPrice: 55000,
    currency: "₹",
    image: "https://lh3.googleusercontent.com/gps-cs-s/AC9h4nqP3F9YGd3Un753l_HAIIRCT-R69GBijnGuraAZ1JsJti9pKW8j5Hcs_hbnHTsS3g2wmFPu2kYw1JtzQZyvbhOMCyMbUjOGzVy0liZZInb4RhNo-LeLUoopWvrykdnej6xWN2Ne=s1360-w1360-h1020-rw",
    inclusions: ["Hotel", "Transfer", "Sightseeing", "Meals", "Permits", "Guide"],
    coordinates: {
      latitude: 27.7000,
      longitude: 88.7000,
      latitudeDelta: 0.8,
      longitudeDelta: 0.8,
    },
    itinerary: [
      {
        day: 1,
        morning: "Arrive and transfer to Gangtok",
        noon: "Rest and permit arrangements",
        evening: "Local market visit",
      },
      {
        day: 2,
        morning: "Transfer to Lachen",
        noon: "Scenic drive via Chungthang",
        evening: "Overnight in Lachen",
      },
      {
        day: 3,
        morning: "Early morning Gurudongmar Lake",
        noon: "Return to Lachen",
        evening: "Rest and recovery",
      },
      {
        day: 4,
        morning: "Transfer to Lachung",
        noon: "Check-in mountain resort",
        evening: "Local village exploration",
      },
      {
        day: 5,
        morning: "Yumthang Valley excursion",
        noon: "Zero Point visit",
        evening: "Return to Lachung",
      },
      {
        day: 6,
        morning: "Return to Gangtok",
        noon: "Afternoon rest",
        evening: "Cultural show",
      },
      {
        day: 7,
        morning: "Gangtok city tour",
        noon: "Rumtek Monastery",
        evening: "Shopping time",
      },
      {
        day: 8,
        morning: "Departure",
        noon: "Airport transfer",
        evening: "",
      },
    ],
    pricing: {
      packageCost: 102000,
      gst: 5100,
      grandTotal: 107100,
      gstPercentage: 5,
    },
    roomsGuests: {
      rooms: 1,
      guests: 2,
    },
    priceCategory: "Premium",
    fromCity: "Bagdogra",
    rating: 4.9,
    reviews: 78,
    description: "High altitude adventure tour to pristine North Sikkim with sacred lakes and breathtaking landscapes.",
  },
  {
    id: 6,
    name: "Kalimpong Gangtok Getaway",
    category: ["Honeymoon", "Couples"],
    duration: 5,
    nights: 4,
    destinations: ["Kalimpong", "Gangtok"],
    startingPrice: 32000,
    currency: "₹",
    image: "https://s3-ap-southeast-1.amazonaws.com/akbartravelsholidays/admin/thumbnail17181062443808gangtok.webp",
    inclusions: ["Hotel", "Transfer", "Sightseeing", "Meals", "Candlelight Dinner"],
    coordinates: {
      latitude: 27.0624,
      longitude: 88.4675,
      latitudeDelta: 0.3,
      longitudeDelta: 0.3,
    },
    itinerary: [
      {
        day: 1,
        morning: "Arrival at Bagdogra",
        noon: "Transfer to Kalimpong",
        evening: "Check-in and romantic dinner",
      },
      {
        day: 2,
        morning: "Kalimpong sightseeing",
        noon: "Deolo Hill, Durpin Monastery",
        evening: "Flower nurseries visit",
      },
      {
        day: 3,
        morning: "Transfer to Gangtok",
        noon: "Cable car ride",
        evening: "MG Marg stroll",
      },
      {
        day: 4,
        morning: "Tsomgo Lake excursion",
        noon: "Couple photography",
        evening: "Special dinner",
      },
      {
        day: 5,
        morning: "Departure",
        noon: "Shopping and airport transfer",
        evening: "",
      },
    ],
    pricing: {
      packageCost: 60000,
      gst: 3000,
      grandTotal: 63000,
      gstPercentage: 5,
    },
    roomsGuests: {
      rooms: 1,
      guests: 2,
    },
    priceCategory: "Romantic",
    fromCity: "Bagdogra",
    rating: 4.7,
    reviews: 145,
    description: "Perfect romantic getaway combining the charm of Kalimpong and the beauty of Gangtok for couples.",
  },
  {
    id: 7,
    name: "Dooars and Gangtok Nature Tour",
    category: ["Wildlife", "Nature"],
    duration: 6,
    nights: 5,
    destinations: ["Lataguri", "Gorumara", "Gangtok"],
    startingPrice: 38000,
    currency: "₹",
    image: "https://paramountclientweb.s3.ap-south-1.amazonaws.com/indian-holiday-trip/Place/2023/Apr/Img_7770_202303031046_Tsuk_la_khang_monastery.jpg",
    inclusions: ["Hotel", "Transfer", "Sightseeing", "Meals", "Safari", "Forest Permits"],
    coordinates: {
      latitude: 26.8467,
      longitude: 89.2167,
      latitudeDelta: 0.4,
      longitudeDelta: 0.4,
    },
    itinerary: [
      {
        day: 1,
        morning: "Arrive NJP",
        noon: "Transfer to Lataguri",
        evening: "Nature walk",
      },
      {
        day: 2,
        morning: "Gorumara National Park safari",
        noon: "Watch tower visit",
        evening: "Tribal cultural program",
      },
      {
        day: 3,
        morning: "Another safari",
        noon: "Transfer to Gangtok",
        evening: "Hill station welcome",
      },
      {
        day: 4,
        morning: "Gangtok city tour",
        noon: "Monastery visits",
        evening: "Cable car ride",
      },
      {
        day: 5,
        morning: "Tsomgo Lake excursion",
        noon: "Yak ride experience",
        evening: "Local shopping",
      },
      {
        day: 6,
        morning: "Departure",
        noon: "Transfer to airport",
        evening: "",
      },
    ],
    pricing: {
      packageCost: 71000,
      gst: 3550,
      grandTotal: 74550,
      gstPercentage: 5,
    },
    roomsGuests: {
      rooms: 1,
      guests: 2,
    },
    priceCategory: "Wildlife Special",
    fromCity: "NJP",
    rating: 4.6,
    reviews: 92,
    description: "Unique combination of wildlife safari in Dooars and hill station experience in Gangtok.",
  },
  {
    id: 8,
    name: "Sikkim Monsoon Special",
    category: ["Nature", "Photography"],
    duration: 4,
    nights: 3,
    destinations: ["Gangtok", "Ravangla"],
    startingPrice: 25000,
    currency: "₹",
    image: "https://www.finderbridge.com/imgs/experiences/explore-the-pelling-sky-walk-and-monastery/main.jpg",
    inclusions: ["Hotel", "Transfer", "Sightseeing", "Meals", "Rain Gear"],
    coordinates: {
      latitude: 27.2690,
      longitude: 88.3915,
      latitudeDelta: 0.2,
      longitudeDelta: 0.2,
    },
    itinerary: [
      {
        day: 1,
        morning: "Arrival in Gangtok",
        noon: "Check-in and rest",
        evening: "Monsoon photography session",
      },
      {
        day: 2,
        morning: "Transfer to Ravangla",
        noon: "Buddha Park visit",
        evening: "Tea garden in rain",
      },
      {
        day: 3,
        morning: "Temi Tea Garden",
        noon: "Return to Gangtok",
        evening: "Local monastery visit",
      },
      {
        day: 4,
        morning: "City tour",
        noon: "Departure preparation",
        evening: "",
      },
    ],
    pricing: {
      packageCost: 47000,
      gst: 2350,
      grandTotal: 49350,
      gstPercentage: 5,
    },
    roomsGuests: {
      rooms: 1,
      guests: 2,
    },
    priceCategory: "Seasonal",
    fromCity: "Gangtok",
    rating: 4.4,
    reviews: 67,
    description: "Experience the unique beauty of Sikkim during monsoon season with lush landscapes and misty mountains.",
  },
  {
    id: 9,
    name: "Spiritual Sikkim Pilgrimage",
    category: ["Spiritual", "Cultural"],
    duration: 6,
    nights: 5,
    destinations: ["Gangtok", "Pelling", "Namchi"],
    startingPrice: 35000,
    currency: "₹",
    image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2b/f3/0e/56/caption.jpg?w=1200&h=1200&s=1",
    inclusions: ["Hotel", "Transfer", "Sightseeing", "Meals", "Spiritual Guide"],
    coordinates: {
      latitude: 27.1666,
      longitude: 88.3639,
      latitudeDelta: 0.4,
      longitudeDelta: 0.4,
    },
    itinerary: [
      {
        day: 1,
        morning: "Arrival and sacred blessing",
        noon: "Ganesh Tok visit",
        evening: "Evening prayers",
      },
      {
        day: 2,
        morning: "Rumtek Monastery",
        noon: "Enchey Monastery",
        evening: "Meditation session",
      },
      {
        day: 3,
        morning: "Transfer to Pelling",
        noon: "Pemayangtse Monastery",
        evening: "Mountain sunset prayers",
      },
      {
        day: 4,
        morning: "Transfer to Namchi",
        noon: "Char Dham complex",
        evening: "Samdruptse statue visit",
      },
      {
        day: 5,
        morning: "Solophok Monastery",
        noon: "Return to Gangtok",
        evening: "Final prayers",
      },
      {
        day: 6,
        morning: "Departure blessing",
        noon: "Airport transfer",
        evening: "",
      },
    ],
    pricing: {
      packageCost: 65000,
      gst: 3250,
      grandTotal: 68250,
      gstPercentage: 5,
    },
    roomsGuests: {
      rooms: 1,
      guests: 2,
    },
    priceCategory: "Spiritual",
    fromCity: "Bagdogra",
    rating: 4.9,
    reviews: 134,
    description: "Sacred journey through Sikkim's most important monasteries and spiritual sites with guided meditation.",
  },
  {
    id: 10,
    name: "Sikkim Winter Wonderland",
    category: ["Winter Sports", "Family with Kids"],
    duration: 5,
    nights: 4,
    destinations: ["Gangtok", "Tsomgo Lake", "Nathu La"],
    startingPrice: 42000,
    currency: "₹",
    image:
      "https://tripxl.com/blog/wp-content/uploads/2024/08/Pemayangtse-Monastery-4.jpg",
    inclusions: ["Hotel", "Transfer", "Sightseeing", "Meals", "Winter Clothing", "Snow Activities"],
    coordinates: {
      latitude: 27.3389,
      longitude: 88.6065,
      latitudeDelta: 0.3,
      longitudeDelta: 0.3,
    },
    itinerary: [
      {
        day: 1,
        morning: "Arrival in snowy Gangtok",
        noon: "Winter clothing setup",
        evening: "Hot chocolate and bonfire",
      },
      {
        day: 2,
        morning: "Snow point excursion",
        noon: "Snowman building activities",
        evening: "Traditional hot dinner",
      },
      {
        day: 3,
        morning: "Frozen Tsomgo Lake visit",
        noon: "Snow photography session",
        evening: "Local cultural program",
      },
      {
        day: 4,
        morning: "Gangtok winter sightseeing",
        noon: "Cable car in snow",
        evening: "Shopping for souvenirs",
      },
      {
        day: 5,
        morning: "Final snow activities",
        noon: "Departure",
        evening: "",
      },
    ],
    pricing: {
      packageCost: 78000,
      gst: 3900,
      grandTotal: 81900,
      gstPercentage: 5,
    },
    roomsGuests: {
      rooms: 1,
      guests: 2,
    },
    priceCategory: "Winter Special",
    fromCity: "Bagdogra",
    rating: 4.8,
    reviews: 98,
    description: "Experience the magical winter beauty of Sikkim with snow-covered landscapes and winter activities.",
  },
];

export default packagesList;